INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (1, "de", "Fähigkeit zu handeln/ausführen");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (2, "de", "Fähigkeit zu beraten");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (3, "de", "Kommunikationsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (4, "de", "Innovationsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (5, "de", "Fähigkeit zur Integration");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (6, "de", "Lernfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (7, "de", "Fähigkeit, Konflikte zu lösen");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (8, "de", "Fähigkeit zu lehren");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (9, "de", "Fähigkeit, die Perspektiven anderer zu verstehen");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (10, "de", "Fähigkeit, in einem Team zu arbeiten");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (11, "de", "Akquisitionsstärke");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (12, "de", "Anpassungsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (13, "de", "Analytische Fähigkeiten");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (14, "de", "Artikulation");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (15, "de", "Bewusstsein für Konsequenzen");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (16, "de", "Konzeptionelle Stärke");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (17, "de", "Gewissenhaftigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (18, "de", "Konsistenz");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (19, "de", "Genossenschaft");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (20, "de", "Kreativität");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (21, "de", "Glaubwürdigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (22, "de", "Entscheidungsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (23, "de", "Delegieren");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (24, "de", "Dialog/Kundenorientierung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (25, "de", "Sorgfalt");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (26, "de", "Disziplin");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (27, "de", "Energie");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (28, "de", "Experimentelle Fähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (29, "de", "Expertise");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (30, "de", "Formative Fähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (31, "de", "Zielorientierte Führung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (32, "de", "Hilfsbereitschaft");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (33, "de", "Ganzheitliches Denken");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (34, "de", "Humor");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (35, "de", "Initiative");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (36, "de", "Andere inspirieren");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (37, "de", "Interdisziplinäres Verständnis");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (38, "de", "Urteil");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (39, "de", "Wissensorientierung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (40, "de", "Loyalität");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (41, "de", "Marktkenntnis");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (42, "de", "Mobilität");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (43, "de", "Objektivität");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (44, "de", "Offenheit für Veränderung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (45, "de", "Optimismus");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (46, "de", "Organisationsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (47, "de", "Beharrlichkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (48, "de", "Eigenverantwortung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (49, "de", "Personalentwicklung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (50, "de", "Planungsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (51, "de", "Problemlösungsfähigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (52, "de", "Berufliche Anerkennung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (53, "de", "Projektmanagement");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (54, "de", "Schlagfertigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (55, "de", "Bereitschaft zum Handeln");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (56, "de", "Beziehungsmanagement");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (57, "de", "Zuverlässigkeit");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (58, "de", "Resilienz");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (59, "de", "Ergebnisorientiertes Handeln");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (60, "de", "Selbstverwaltung");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (61, "de", "Pflichtbewusstsein");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (62, "de", "Soziales Engagement");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (63, "de", "Systematisch-methodisches Vorgehen");
INSERT INTO `restfx`.`language` (`id`, `lang`, `name`) VALUES (64, "de", "Wertorientierung");